# Generated by Django 3.2.4 on 2022-09-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('usercat', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('alternate_number', models.CharField(blank=True, max_length=255, null=True)),
                ('hostel', models.CharField(max_length=255)),
                ('pendingexeats', models.CharField(max_length=255)),
                ('approvedexeats', models.CharField(max_length=255)),
                ('rejectedexeats', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('notification', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('exeat_type', models.CharField(max_length=255)),
                ('exeat_description', models.CharField(max_length=255)),
                ('departure_date', models.CharField(max_length=255)),
                ('arrival_date', models.CharField(max_length=255)),
                ('hostel', models.CharField(max_length=255)),
                ('statusPorter', models.CharField(max_length=255)),
                ('statusParent', models.CharField(max_length=255)),
                ('statusStudentAffairs', models.CharField(max_length=255)),
                ('iscancelled', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=255)),
                ('parent_phone_no', models.CharField(max_length=255)),
                ('alternate_parent_phone_no', models.CharField(max_length=255)),
                ('parent_email', models.CharField(max_length=255)),
                ('student_level', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('matric_no', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['student_level'],
            },
        ),
    ]
