# Generated by Django 3.2.4 on 2022-09-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='alternate_parent_phone_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
