# Generated by Django 3.2.4 on 2022-09-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_alternate_parent_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='statusPorter',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
