# Generated by Django 3.2.4 on 2022-09-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_forms_statusporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='statusPorter',
            field=models.CharField(max_length=255),
        ),
    ]
