# Generated by Django 3.2.4 on 2022-09-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_forms_statusporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='date_added',
            field=models.CharField(max_length=255),
        ),
    ]
