# Generated by Django 3.2.4 on 2022-09-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_allusers_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='studentpic',
            field=models.CharField(blank=True, max_length=625, null=True),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
