# Generated by Django 3.2.4 on 2022-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220914_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='parent_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='parentemail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='students_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
