# Generated by Django 3.2.4 on 2022-09-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220914_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
