# Generated by Django 3.2.4 on 2022-09-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_allusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='usercat',
            field=models.CharField(choices=[('student', 'student'), ('porter', 'porter'), ('parent', 'parent'), ('sa', 'sa')], max_length=255),
        ),
        migrations.AlterField(
            model_name='forms',
            name='statusParent',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='forms',
            name='statusPorter',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='forms',
            name='statusStudentAffairs',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
