# Generated by Django 4.1 on 2022-09-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20220915_1251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forms",
            name="statusParent",
            field=models.CharField(
                choices=[("0", "0"), ("1", "1"), ("2", "2")],
                default="0",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="forms",
            name="statusStudentAffairs",
            field=models.CharField(
                choices=[("0", "0"), ("1", "1"), ("2", "2")],
                default="0",
                max_length=255,
            ),
        ),
    ]
