# Generated by Django 4.1 on 2022-09-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_forms_statusparent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allusers",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("non-binary", "non-binary"),
                ],
                default=" ",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
