# Generated by Django 4.1 on 2022-09-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_allusers_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allusers",
            name="approvedexeats",
            field=models.CharField(default="0", max_length=255),
        ),
        migrations.AlterField(
            model_name="allusers",
            name="pendingexeats",
            field=models.CharField(default="0", max_length=255),
        ),
        migrations.AlterField(
            model_name="allusers",
            name="rejectedexeats",
            field=models.CharField(default="0", max_length=255),
        ),
    ]
