# Generated by Django 4.1 on 2022-09-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_forms_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forms",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "100"),
                    ("200", "200"),
                    ("300", "300"),
                    ("400", "400"),
                ],
                default="",
                max_length=255,
            ),
        ),
    ]
