# Generated by Django 4.1 on 2022-09-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_forms_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="tag",
            field=models.CharField(
                choices=[
                    ("primary", "primary"),
                    ("danger", "danger"),
                    ("success", "success"),
                ],
                default="",
                max_length=255,
            ),
        ),
    ]
