# Generated by Django 4.1 on 2022-09-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_events_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="tag",
            field=models.CharField(
                choices=[
                    ("primary", "primary"),
                    ("danger", "danger"),
                    ("success", "success"),
                ],
                default="primary",
                max_length=255,
            ),
        ),
    ]
