# Generated by Django 3.2.4 on 2022-10-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20221020_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='is_default_pass',
            field=models.BooleanField(default=True),
        ),
    ]
