# Generated by Django 3.2.4 on 2022-10-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_allusers_is_default_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='forms_left',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_form_sent_day',
        ),
        migrations.AddField(
            model_name='allusers',
            name='forms_left',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2)], default=2, max_length=255),
        ),
        migrations.AddField(
            model_name='allusers',
            name='last_form_sent_day',
            field=models.CharField(default='', max_length=255),
        ),
    ]
