# Generated by Django 3.2.4 on 2022-10-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20221024_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='date_added_main',
            field=models.CharField(default='', max_length=255),
        ),
    ]
