# Generated by Django 3.2.4 on 2022-10-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_allusers_date_added_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='forms_left',
            field=models.CharField(max_length=255),
        ),
    ]
