# Generated by Django 3.2.4 on 2022-10-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='', max_length=255)),
                ('hostel_name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
