# Generated by Django 3.2.4 on 2022-10-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_hostels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255),
        ),
    ]
