# Generated by Django 3.2.4 on 2022-10-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_hostels_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='date_added_main',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='forms_left',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='last_form_sent_day',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
