# Generated by Django 3.2.4 on 2022-10-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20221025_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='usercat',
            field=models.CharField(choices=[('student', 'student'), ('porter', 'porter'), ('parent', 'parent'), ('sa', 'sa'), ('security', 'security')], max_length=255),
        ),
    ]
