# Generated by Django 3.2.4 on 2022-10-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='department',
            field=models.CharField(default='', max_length=255),
        ),
    ]
