# Generated by Django 3.2.4 on 2023-01-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20221218_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
