# Generated by Django 3.2.4 on 2023-01-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_allusers_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='College',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='departments',
            new_name='colleges',
        ),
        migrations.AddField(
            model_name='forms',
            name='college',
            field=models.CharField(choices=[('COPAS', 'C.O.P.A.S.'), ('CASMAS', 'C.A.S.M.A.S.'), ('COLENSMAS', 'C.O.L.E.N.S.M.A.S')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(choices=[('COPAS', 'C.O.P.A.S.'), ('CASMAS', 'C.A.S.M.A.S.'), ('COLENSMAS', 'C.O.L.E.N.S.M.A.S')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='usercat',
            field=models.CharField(choices=[('student', 'student'), ('porter', 'porter'), ('parent', 'parent'), ('saffairs', 'saffairs'), ('security', 'security'), ('superuser', 'superuser')], max_length=255),
        ),
    ]
