# Generated by Django 3.2.4 on 2023-01-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='departments',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
