# Generated by Django 4.1 on 2023-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="forms",
            name="home_address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="allusers",
            name="gender",
            field=models.CharField(
                choices=[("", ""), ("male", "male"), ("female", "female")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="allusers",
            name="usercat",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("student", "student"),
                    ("porter", "porter"),
                    ("parent", "parent"),
                    ("saffairs", "saffairs"),
                    ("security", "security"),
                    ("superuser", "superuser"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="forms",
            name="college",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("COPAS", "C.O.P.A.S."),
                    ("CASMAS", "C.A.S.M.A.S."),
                    ("COLENSMAS", "C.O.L.E.N.S.M.A.S"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="forms",
            name="level",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("100", "100"),
                    ("200", "200"),
                    ("300", "300"),
                    ("400", "400"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="forms",
            name="statusParent",
            field=models.CharField(
                choices=[("", ""), ("0", "0"), ("1", "1"), ("2", "2")],
                default="0",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="forms",
            name="statusPorter",
            field=models.CharField(
                choices=[("", ""), ("0", "0"), ("1", "1"), ("2", "2")],
                default="0",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="forms",
            name="statusStudentAffairs",
            field=models.CharField(
                choices=[("", ""), ("0", "0"), ("1", "1"), ("2", "2")],
                default="0",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="hostels",
            name="gender",
            field=models.CharField(
                choices=[("", ""), ("male", "male"), ("female", "female")],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="college",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("COPAS", "C.O.P.A.S."),
                    ("CASMAS", "C.A.S.M.A.S."),
                    ("COLENSMAS", "C.O.L.E.N.S.M.A.S"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="tickets",
            name="priority",
            field=models.IntegerField(default=3),
        ),
    ]
