# Generated by Django 4.1 on 2023-01-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_forms_home_address_alter_allusers_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forms",
            name="home_address",
        ),
        migrations.AddField(
            model_name="allusers",
            name="home_address",
            field=models.CharField(default="", max_length=255),
        ),
    ]
