# Generated by Django 3.2.4 on 2023-01-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_forms_home_address_allusers_home_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='forms_left',
            field=models.CharField(default='2', max_length=255),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='home_address',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
